name: Matrix Release Trigger

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
#    if: startsWith(github.ref, 'refs/tags/v')
#    outputs:
#      tag_version: ${{ steps.extract_tag.outputs.tag_version }}
    steps:
      - name: prepare test
        run: |
          echo "test"
#          TAG_VERSION=${GITHUB_REF#refs/tags/}
#          echo "tag_version=$TAG_VERSION" >> $GITHUB_OUTPUT

  trigger-workflows:
    strategy:
      matrix:
        env: [dev, stg, prod]
    uses: ./.github/workflows/deploy.yml
    with:
      env: ${{ matrix.env }}

#
#    steps:
#      - name: Trigger ${{ matrix.workflow.name }}
#        uses: actions/github-script@v7
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          script: |
#            const inputs = {
#              version: '${{ needs.prepare.outputs.tag_version }}',
#              ...${{ toJson(matrix.workflow.config) }}
#            };
#
#            await github.rest.actions.createWorkflowDispatch({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              workflow_id: '${{ matrix.workflow.name }}',
#              ref: 'main',
#              inputs: inputs
#            });
#
#            console.log(`Triggered ${matrix.workflow.name} with inputs:`, inputs);
