name: Matrix Release Trigger

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
#    if: startsWith(github.ref, 'refs/tags/v')
#    outputs:
#      tag_version: ${{ steps.extract_tag.outputs.tag_version }}
    steps:
      - name: Extract tag version
        run: |
          echo "test"
#          TAG_VERSION=${GITHUB_REF#refs/tags/}
#          echo "tag_version=$TAG_VERSION" >> $GITHUB_OUTPUT

#  trigger-workflows:
#    needs: prepare
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        workflow:
#          - name: 'deployment.yml'
#            config:
#              environment: 'production'
#              deploy_config: 'prod-config-1'
#          - name: 'deployment.yml'
#            config:
#              environment: 'staging'
#              deploy_config: 'staging-config-1'
#          - name: 'integration-tests.yml'
#            config:
#              test_suite: 'full'
#              parallel_jobs: '4'
#
#    steps:
#      - name: Trigger ${{ matrix.workflow.name }}
#        uses: actions/github-script@v7
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          script: |
#            const inputs = {
#              version: '${{ needs.prepare.outputs.tag_version }}',
#              ...${{ toJson(matrix.workflow.config) }}
#            };
#
#            await github.rest.actions.createWorkflowDispatch({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              workflow_id: '${{ matrix.workflow.name }}',
#              ref: 'main',
#              inputs: inputs
#            });
#
#            console.log(`Triggered ${matrix.workflow.name} with inputs:`, inputs);
